# Basic
title: Axag Life
subtitle: 每一刻的人生 都值得记录
welcome_message: 欢迎来到我的Blog
description: 主业:iOS开发者 略懂游戏,健身的伪90后.
creator: <a href="https://axag.fun">@a_xiang</a>

url: "https://axag.fun"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 我的简历, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: axagfun
    # duoshuo: 
    
# Social
social:
    weibo: _阿翔翔
    github: ssuperdreamer
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: ssuperdreamer@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
